# Основные настройки сайта
title: Pavel Tarkhov # название сайта
description: >- # описание сайта
  He's writing in Bahasa about web technology and experience as a journal 
  for documentation things that he learned, meet him <a href="https://github.com/piharpi" target="_blank" rel="noopener">@github</a>.
lang: en-US # язык сайта по умолчанию
timezone: Asia/Jakarta # часовой пояс
image: assets/img/ogp.png # изображение для Open Graph протокола
mode: dark # тема оформления "dark" или "light"

# Настройки профиля
author:
  name: Pavel Tarkhov # имя автора
  bio: >- # описание автора
    Это мой сайт с портфолио моих работ в разных отраслях связанных с дизайном, видеомонтажом и 3D моделированием.
    <a href="https://t.me/pavel_tarkhov" target="_blank" rel="noopener">Мой Telegram</a>.
  username: username # общее имя пользователя
  github: github_username # имя пользователя GitHub
  Telegram: pavel_tarkhov # имя пользователя Telegram
  facebook: facebook_username # имя пользователя Facebook
  email: your-email@email.com # адрес электронной почты
  avatar: /assets/img/avatar.jpg # путь к аватару

# Настройки URL
url: "https://klise.now.sh" # основной URL сайта
baseurl: # базовый URL (если сайт в подкаталоге)
permalink: /:title/ # формат ссылок на посты
google_analytics: # ID Google Analytics
fb_appid: # ID приложения Facebook

# Настройки коллекций
collections:
  posts:
    output: true # генерировать страницы для постов

# Настройки Markdown
markdown: kramdown # процессор markdown
highlighter: rouge # подсветка синтаксиса
kramdown:
  syntax_highlighter: rouge

# Настройки по умолчанию для страниц
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false

# Настройки Jekyll Compose для новых постов
jekyll_compose:
  post_default_front_matter: # значения по умолчанию для новых постов
    modified:
    tags: []
    description:
  draft_default_front_matter: # значения по умолчанию для черновиков
    modified:
    tags: []
    description:

# Ограничение количества постов на главной
number_of_posts: 5

# Настройки сборки
sass:
  style: compressed # сжатие CSS

# Файлы для включения
include:
  - _redirects
  - .htaccess

# Файлы для исключения из сборки
exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - lighthouse.png
  - klise-*.gem
  - klise.gemspec

# Плагины Jekyll
plugins:
  - jekyll-feed # RSS-лента
  - jekyll-sitemap # генерация карты сайта
  - jekyll-postfiles # поддержка файлов в постах
